- name: Update Nginx to a Specific Version
  hosts: localhost
  become: true
  vars:
  
    nginx_version: "1.18.0"

  tasks:
    - name: Add the official Nginx repository (if not already added)
      apt_repository:
        repo: "ppa:nginx/stable"
        state: present
      

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install the specified version of Nginx
      apt:
        name: "nginx={{ nginx_version }}"
        state: present

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Verify the installed Nginx version
      command: nginx -v
      register: nginx_version_check
      changed_when: false

    - name: Show Nginx version
      debug:
        msg: "Installed Nginx version: {{ nginx_version_check.stderr }}"